# This is a basic workflow that is manually triggered

name: env file testing workflow
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  validate_vars:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: test
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: test
      shell: bash
      run: |
        echo "secrets are: ${{ vars.TEST }}"
